Repository pre-onboarding-frontend-7-team-3/pre-onboarding-7th-3-2-3, pull requests merged in 2022-11, with the labels that each got.

#4 [ Fix ] 토큰 유무 리다이렉트 처리
  src/App.tsx
  src/pages/NotFound/NotFound.style.ts
  src/pages/NotFound/NotFound.tsx
Labels: bug, fix

#10 [ Feat ] 신규 고객 생성 모달
  package-lock.json
  package.json
  src/components/InvestmentAccountList/Account-query/InvestmentAccount.query.ts
  src/components/InvestmentAccountList/Account-query/InvestmentAccount.repository.ts
  src/components/InvestmentAccountList/Dropdown/Dropdown.style.ts
  src/components/InvestmentAccountList/InvestmentAccountList.tsx
  src/components/InvestmentAccountList/component/SearchInput.tsx
  src/components/LoginForm/LoginErrorModal/LoginErrorModal.tsx
  src/components/NewUserModal/FileInput/FileInput.style.ts
  src/components/NewUserModal/FileInput/FileInput.tsx
  src/components/NewUserModal/FunnelButton/FunnelButton.style.ts
  src/components/NewUserModal/FunnelButton/FunnelButton.tsx
  src/components/NewUserModal/NewUserModal.style.ts
  src/components/NewUserModal/NewUserModal.tsx
  src/components/NewUserModal/index.ts
  src/constants/dropDownData.ts
  src/constants/funnelButtonData.ts
  src/constants/tableData.ts
  src/hooks/useUnmountIfClickedOutside.ts
Labels: feat

#15 [Feat] 공통 table head , body 구현
  src/components/Users/UserList.tsx
  src/components/common/Table/CustomTableBody.tsx
  src/components/common/Table/CustomTableHead.tsx
  src/constants/tableData.ts
Labels: feat

#14 [ Feat ] 신규 사용자 생성 모달
  src/components/InvestmentAccountList/Account-query/InvestmentAccount.query.ts
  src/components/InvestmentAccountList/Account-query/InvestmentAccount.repository.ts
  src/components/InvestmentAccountList/InvestmentAccountList.tsx
  src/components/InvestmentAccountList/component/SearchInput.tsx
  src/components/LoginForm/LoginErrorModal/LoginErrorModal.tsx
  src/components/NewUserModal/FileInput/FileInput.style.ts
  src/components/NewUserModal/FileInput/FileInput.tsx
  src/components/NewUserModal/FunnelButton/FunnelButton.style.ts
  src/components/NewUserModal/FunnelButton/FunnelButton.tsx
  src/components/NewUserModal/NewUserModal.style.ts
  src/components/NewUserModal/NewUserModal.tsx
  src/components/NewUserModal/UserInput/UserInput.style.ts
  src/components/NewUserModal/UserInput/UserInput.tsx
  src/components/NewUserModal/api/NewUserModal.query.ts
  src/components/NewUserModal/api/NewUserModal.repository.ts
  src/components/NewUserModal/index.ts
  src/components/Users/UserList-query/UserList.query.ts
  src/components/Users/UserList-query/UserList.repository.ts
  src/components/Users/UserList-query/UserListFilteredByKeyword.query.ts
  src/components/Users/UserList-query/UserListFilteredByKeyword.repository.ts
  src/components/Users/UserList.tsx
  src/components/Users/UserTableItem/UserTableItem.tsx
  src/constants/NewUserInputData.ts
  src/constants/dropDownData.ts
  src/constants/funnelButtonData.ts
  src/constants/tableData.ts
  src/hooks/useUnmountIfClickedOutside.ts
  src/libs/api/client.ts
Labels: feat

#21 [ Feat ] 사용자 목록 필터링 API
  src/components/InvestmentAccountList/Account-query/FilteredInvestmentAccount.query.ts
  src/components/InvestmentAccountList/Account-query/FilteredInvestmentAccountByName.repository.ts
  src/components/InvestmentAccountList/Account-query/InvestmentAccount.repository.ts
  src/components/InvestmentAccountList/InvestmentAccountList.tsx
  src/components/InvestmentAccountList/component/SearchInput.tsx
  src/components/Users/UserList-query/UserList.repository.ts
  src/components/Users/UserList-query/UserListFilteredByKeyword.query.ts
  src/components/Users/UserList-query/UserListFilteredByKeyword.repository.ts
  src/components/Users/UserList.tsx
  src/components/Users/UserTableItem/UserTableItem.tsx
  src/components/common/Table/CustomTableBody.tsx
Labels: feat

#23 [ Style ] 공용컴포넌트 분리/인라인스타일 분리
  src/App.tsx
  src/components/InvestmentAccountList/InvestmentAccountList.tsx
  src/components/InvestmentAccountList/InvestmentAccountTableHead/InvestmentAccountTableHead.tsx
  src/components/InvestmentAccountList/PagenationButton/PagenationButton.tsx
  src/components/NewUserModal/NewUserModal-query/NewUserModal.query.ts
  src/components/NewUserModal/NewUserModal-query/NewUserModal.repository.ts
  src/components/NewUserModal/NewUserModal.style.ts
  src/components/NewUserModal/NewUserModal.tsx
  src/components/UserDetail/UserDetailTableItem.tsx
  src/components/UserList/UserList-query/UserList.model.ts
  src/components/UserList/UserList-query/UserList.query.ts
  src/components/UserList/UserList-query/UserList.repository.ts
  src/components/UserList/UserList.style.ts
  src/components/UserList/UserList.tsx
  src/components/UserList/UserTableHead/UserTable.tsx
  src/components/UserList/UserTableItem/UserTableItem.tsx
  src/components/UserList/index.ts
  src/components/Users/UserTableHead/UserTable.tsx
  src/components/Users/index.ts
  src/components/common/Dropdown/Dropdown.style.ts
  src/components/common/Dropdown/Dropdown.tsx
  src/components/common/SearchInput/SearchInput.style.ts
  src/components/common/SearchInput/SearchInput.tsx
  src/components/common/Table/CustomTableBody.style.ts
  src/components/common/Table/CustomTableBody.tsx
  src/components/common/Table/CustomTableHead.tsx
  src/components/index.ts
  src/constants/UserTableData.ts
  src/hooks/useDebounce.ts
  src/pages/DashBoard/DashBoard.tsx
  src/pages/DashBoard/index.ts
  src/pages/UserDetail/UserDetail.tsx
  src/pages/UserDetail/index.ts
  src/pages/UserDetailPage/index.ts
  src/pages/UserList/UserList.tsx
  src/pages/UserList/index.ts
  src/pages/users/index.ts
Labels: style

#22 [ Feat ] 사용자 상세 페이지 내 정보 수정 구현
  src/components/InvestmentAccountList/InvestmentAccountItem/InvestmentAccountItem.tsx
  src/components/InvestmentAccountList/InvestmentAccountList.tsx
  src/components/InvestmentAccountList/InvestmentAccountTableHead/InvestmentAccountTableHead.tsx
  src/components/UserDetail/UserDetail.tsx
  src/components/UserDetail/UserDetailTableHead.tsx
  src/components/UserDetail/UserDetailTableItem.tsx
  src/components/UserDetail/UserInfoTable.tsx
  src/components/UserDetail/hooks/useEditUserDetail.ts
  src/constants/tableData.ts
  src/libs/api/user.ts
  src/pages/UserDetail/UserDetail.tsx
Labels: feat

#26 [ Feat ] 신규 사용자 생성 예외처리
  src/components/InvestmentAccountList/Account-query/InvestmentAccount.repository.ts
  src/components/LoginForm/LoginInput/LoginInput.tsx
  src/components/NewUserModal/FileInput/FileInput.tsx
  src/components/NewUserModal/FunnelButton/FunnelButton.style.ts
  src/components/NewUserModal/FunnelButton/FunnelButton.tsx
  src/components/NewUserModal/NewUserModal-query/NewUserModal.query.ts
  src/components/NewUserModal/NewUserModal-query/NewUserModal.repository.ts
  src/components/NewUserModal/NewUserModal.style.ts
  src/components/NewUserModal/NewUserModal.tsx
  src/components/NewUserModal/UserInput/UserInput.style.ts
  src/components/NewUserModal/UserInput/UserInput.tsx
  src/components/UserDetail/UserDetail.tsx
  src/components/UserDetail/UserDetailTableItem.tsx
  src/components/UserDetail/UserInfoTable.tsx
  src/components/UserDetail/hooks/useUserDetail.ts
  src/components/UserList/UserTableItem/UserTableItem.tsx
  src/constants/NewUserInputData.ts
  src/constants/UserTableData.ts
  src/utils/auth/httpResponseUtils.ts
  src/utils/auth/validator.ts
  src/utils/convertDate.ts
  src/utils/validator.ts
Labels: feat

#32 [ Fix ] access_token 처리를 cookies에서. ( + expire time 추가 )
  package-lock.json
  package.json
  src/App.tsx
  src/components/LoginForm/LoginForm.tsx
  src/components/UserList/UserList.tsx
  src/components/common/Sider/Sider.tsx
  src/libs/api/client.ts
  src/utils/auth/RequireAuth.tsx
  src/utils/storage/webStorageUtils.ts
Labels: feat

#37 [ Feat ] Loader Component 추가
  package-lock.json
  package.json
  src/components/InvestmentAccountList/InvestmentAccountList.tsx
  src/components/UserDetail/UserDetail.tsx
  src/components/UserList/UserList.tsx
  src/components/common/Loader/Loader.style.ts
  src/components/common/Loader/Loader.tsx
  src/components/common/Table/CustomTableBody.tsx
Labels: feat

#39 Feature/investment accounts
  package-lock.json
  package.json
  src/components/NewUserModal/FileInput/FileInput.tsx
  src/components/NewUserModal/NewUserModal-query/NewUserModal.query.ts
  src/components/NewUserModal/UserInput/UserInput.tsx
  src/components/UserDetail/UserInfoTable.tsx
  src/components/common/Loader/Loader.style.ts
  src/components/common/Loader/Loader.tsx
  src/components/common/SEO/SEO.tsx
  src/pages/InvestmentAccounts/InvestmentAccounts.tsx
  src/pages/InvestmentAccounts/index.ts
  src/pages/NotFound/NotFound.style.ts
  src/pages/NotFound/NotFound.tsx
  src/pages/UserDetail/UserDetail.tsx
  src/pages/UserList/UserList.tsx
  src/pages/login/Login.tsx
  src/pages/login/index.ts
Labels: feat, fix

#42 [ Refactor ] Login API
  src/components/LoginForm/Login-query/Login.query.ts
  src/components/LoginForm/Login-query/Login.repository.ts
  src/components/LoginForm/LoginForm.tsx
  src/components/LoginForm/api/handleQueryLogin.ts
  src/components/UserList/UserList-query/UserList.query.ts
  src/components/common/Sider/Sider.tsx
  src/libs/api/client.ts
Labels: refactor

#48 [ Refactor ] 타입 지정/API 함수 @src/shared에서 관리
  package-lock.json
  package.json
  src/apis/httpClient.ts
  src/components/InvestmentAccountList/Account-query/InvestmentAccount.model.ts
  src/components/InvestmentAccountList/InvestmentAccountList.style.ts
  src/components/InvestmentAccountList/InvestmentAccountList.tsx
  src/components/LoginForm/LoginForm.tsx
  src/components/NewUserModal/NewUserModal.tsx
  src/components/UserDetail/UserInfoTable.tsx
  src/components/UserList/UserList.tsx
  src/components/common/SEO/SEO.tsx
  src/libs/api/auth.ts
  src/shared/Account-query/Account.model.ts
  src/shared/Account-query/Account.query.ts
  src/shared/Account-query/Account.repository.ts
  src/shared/Login-query/Login.model.ts
  src/shared/Login-query/Login.query.ts
  src/shared/Login-query/Login.repository.ts
  src/shared/User-query/User.model.ts
  src/shared/User-query/User.query.ts
  src/shared/User-query/User.repository.ts
  src/styled.d.ts
  src/utils/assetsColorDecider.ts
  src/utils/auth/httpResponseUtils.ts
Labels: refactor
